name: Package Chrome Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Create extension package (ZIP)
        run: |
          echo "Creating Chrome extension ZIP package..."
          mkdir -p dist
          # Create zip directly from files without creating nested folders
          cd $(pwd) && zip -r dist/random-beep.zip background icons lib options popup sounds statistics storage utils _locales manifest.json offscreen.html offscreen.js
      
      - name: Create extension package (CRX)
        run: |
          echo "Creating Chrome extension CRX package..."
          # Generate a key if not exists (will be used for testing only)
          if [ ! -f dist/key.pem ]; then
            openssl genrsa -out dist/key.pem 2048
          fi
          
          # Install crx3-utils for CRX creation
          npm install -g crx3-cli
          
          # Build the CRX file
          crx3 -p dist/key.pem -o dist/random-beep.crx background icons lib options popup sounds statistics storage utils _locales manifest.json offscreen.html offscreen.js
      
      - name: Upload extension packages as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: random-beep-extension
          path: |
            dist/random-beep.zip
            dist/random-beep.crx
      
      - name: Create release if tagged version
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Creating release for version $VERSION"
          gh release create "${{ github.ref_name }}" \
            --title "Random Beep v$VERSION" \
            --notes "Release of version $VERSION. See CHANGELOG.md for details." \
            dist/random-beep.zip \
            dist/random-beep.crx 